version: 0.2
 
phases:
             
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo Installing source NPM dependencies..
      - npm install
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 496746411336.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=496746411336.dkr.ecr.us-east-1.amazonaws.com/nodeapp
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"nodeapp","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
